Aggiunta visualizzazione tipologie
italia/design-scuole-pagine-statiche pull request #62
Opened 2023-09-06 09:51 UTC by sviluppoRobyone

Aggiunta della tipologia documento e tipologia circolare nell'apertura delle pagine foglia, come previsto da modello architettura scuole

Fix #61

2023-12-11 20:45 UTC, zetareticoli approved these changes

2023-12-22 15:11 UTC, astagi requested changes
@sviluppoRobyone perchè la modifica nel `package.json`?

2024-01-08 14:33 UTC, astagi commented
@sviluppoRobyone rimuovere le modifiche al `package.json` per favore

2024-01-29 16:35 UTC, zetareticoli approved these changes

2024-03-08 16:18 UTC, zetareticoli approved these changes

2024-05-08 06:59 UTC, sviluppoRobyone commented
è necessario svolgere qualche modifica da parte nostra?

2024-05-08 09:17 UTC, zetareticoli approved these changes

2024-05-08 09:18 UTC, zetareticoli commented
> è necessario svolgere qualche modifica da parte nostra?

@astagi chiedeva di rimuovere la modifica al file `package.json`

2024-05-08 09:55 UTC, sviluppoRobyone commented
A me risultano rimosse, vi risulta?

2024-05-08 16:21 UTC, zetareticoli commented
> A me risultano rimosse, vi risulta?

corretto, @astagi se approvi "liberiamo" questa PR per un prossimo merge :)

2024-05-13 16:34 UTC, merged