Restyle panoramica didattica
italia/design-scuole-pagine-statiche pull request #70
Opened 2024-01-03 08:49 UTC by rcoopcsc

Uniformati gli stili delle card del carosello, aggiunto lo sfondo, corrette le classi per mostrare come badge gli argomenti

2024-01-03 09:23 UTC, zetareticoli requested changes
@rcoopcsc l'alternanza di sfondi che hai applicato va rivista, poiché la sezione "Esplora risorse" ha un colore che contrasta male con la sezione successiva. Il mio consiglio è di usare il bianco.

C'è poi uno sfondo verde chiaro che appare quando i pattern grafici finiscono in altezza.

2024-01-03 10:27 UTC, rcoopcsc commented
Ciao @zetareticoli ora come ti sembra? A me non dispiace così. Oppure, si potrebbe fare una cosa ancora più neutra, alternando lo sfondo delle sezioni con quell'effetto bg-light/bg-white/bg-light.. un po' come nella panoramica delle notizie.

2024-01-03 11:15 UTC, zetareticoli requested changes
Resta da rimuovere lo sfondo verde chiaro sotto la CTA dedicata a tutti i progetti

2024-01-03 15:03 UTC, rcoopcsc commented
@zetareticoli così può andare?

2024-01-04 08:51 UTC, zetareticoli approved these changes

2024-01-04 16:21 UTC, zetareticoli commented
@astagi per ora procedo con merge, poi vediamo quando fare nuovo rilascio

2024-01-04 16:21 UTC, merged