Rimozione maiuscolo, bugs, pagina le persone
italia/design-scuole-pagine-statiche pull request #75
Opened 2024-05-30 12:10 UTC by sviluppoRobyone

Vista la richiesta di più asseveratori, viste le indicazioni di Design System .Italia (https://designers.italia.it/design-system/fondamenti/linguaggio/) e linee guida di linguaggio () sull'evitare maiuscolo e moderare le parole straniere, abbiamo apportato alcune correzioni conseguenti. 
Una volta approvate andremo ad effettuare le stesse modifiche nel tema Wordpress (dove ancora non sono presenti).

Abbiamo altresì corretto alcuni bug e allineato la pagina Le persone al modello architetturale (come già avviene all'interno del tema Wordpress).

2024-05-30 16:12 UTC, arturu commented
Vorrei fare una considerazione su un punto specifico: la modifica alla pagina delle persone. Nella versione attuale (https://italia.github.io/design-scuole-pagine-statiche/scuole-sezione-persone.html), è immediatamente chiaro chi sono i responsabili delle varie strutture, informazioni vitali per chi vive la scuola quotidianamente. Pensa che siamo a fine anno e devo ancora chiedere in giro chi è il responsabile di quel plesso o di quella commissione.

Nella versione proposta (https://design-scuole-pagine-sta-git-760ed4-dip-trasformazione-digitale.vercel.app/scuole-sezione-persone.html) c'è una suddivisione piuttosto semplicistica tra dirigente, docenti e personale non docente, informazioni che sono di scarsa utilità per la comunità scolastica. Sono cose che già si sanno e non necessitano di un sito web per essere conosciute.

Alla luce di ciò, propongo di non cambiare la struttura della pagina delle persone, poiché diventerebbe inutile e scarsamente informativa. Mantenendo l'attuale struttura, è subito evidente chi sono i responsabili delle varie strutture. Queste informazioni permettono alle famiglie, ai nuovi docenti (supplenti) e ai docenti veterani di conoscere i cambiamenti all'inizio dell'anno scolastico, quando vengono nominati i nuovi responsabili.

Per il resto grandioso :)

2024-05-31 06:02 UTC, arturu requested changes
Certosino e preciso lavoro. Unica cosa, come detto in altri commenti, propongo di non cambiare la struttura della pagina persone.

2024-05-31 06:02 UTC, arturu commented on src/scuole-sezione-persone.html
Propongo di non cambiare la struttura delle informazioni, la struttura proposta fornisce informazioni di scarso interesse.

2024-05-31 06:33 UTC, sviluppoRobyone commented
Buongiorno, per quanto riguarda il modello della pagina Le persone, si tratta solo di un allineamento ad architettura, non sono quindi nostre idee.

Utilizziamo il tema Wordpress (https://github.com/italia/design-scuole-wordpress-theme) e abbiamo a nostra volta subito questo cambiamento (basato sulle indicazioni che vengono date nel modello architetturale, che prevedono appunto una mera lista di persone divise per ruolo).

Vista la necessità di intervenire, abbiamo pensato fosse buona cosa rendere uniformi le indicazioni, però se emerge che si può tornare indietro, per noi non ci sono problemi, riportiamo indietro anche il tema Wordpress ;)

Di sicuro gli amministratori sapranno darci chiarimenti @zetareticoli @astagi

2024-05-31 07:34 UTC, arturu commented
> Buongiorno, per quanto riguarda il modello della pagina Le persone, si tratta solo di un allineamento ad architettura, non sono quindi nostre idee.
> 
> Utilizziamo il tema Wordpress (https://github.com/italia/design-scuole-wordpress-theme) e abbiamo a nostra volta subito questo cambiamento (basato sulle indicazioni che vengono date nel modello architetturale, che prevedono appunto una mera lista di persone divise per ruolo).

Ciao! :)

Capisco che se è una cosa obbligata, va accettata. Però, prima di procedere, concediamoci 5 minuti di riflessione.

Per ulteriori spunti vorrei segnalare questo test: https://test.icmarvasivizzone.edu.it/scuola/le-persone (con dati sintetici), in linea con https://italia.github.io/design-scuole-pagine-statiche/scuole-sezione-persone.html. Qui è subito chiaro chi sono i responsabili di ogni struttura.

Avere una pagina che presenta in modo organizzato tutti i responsabili delle strutture è molto prezioso, perché queste informazioni sono frequentemente necessarie durante l'anno scolastico. Ad esempio, l'altro giorno un candidato privatista agli esami di stato doveva parlare con il responsabile della commissione esami. Ci sono volute numerose telefonate per scoprire chi fosse, nonostante io lavori in quella scuola.

Per contro, avere una suddivisione per dirigente, docenti e non docenti non offre informazioni di valore. Bene o male, si sa chi è il dirigente, gli insegnanti e il personale ATA, e chi non lo sa può ottenere questa informazione in brevissimo tempo.

Spero che queste ulteriori riflessioni siano utili e non tediose. :)

2024-05-31 14:08 UTC, akamizi commented
Concordo con quanto detto da @arturu la soluzione "vecchia" mi sembra la più corretta, con le informazioni più "trovabili" se mi permettete l'uso non perfettamente corretto del termine.
Ecco come è visualizzata sul nostro sito: https://www.liceomorgagni.edu.it/scuola/le-persone

2024-05-31 14:29 UTC, sviluppoRobyone commented
Per evitare fraintendimenti, la questione non riguarda il merito ma proprio l'aderenza al modello architetturale (che poi è vincolante per i finanziamenti europei 1.4.1 scuole).

1-Indice
![image](https://github.com/italia/design-scuole-pagine-statiche/assets/13221786/f7821200-6282-4b60-b166-75d2b5632f7f)

2-Alberatura
![image](https://github.com/italia/design-scuole-pagine-statiche/assets/13221786/efb15f46-e6d3-4f6d-982f-b98044ccbde2)

Qualora si possa modificare il modello architetturale, a noi va benissimo tenere com'è o comunque fare riflessioni in merito. Riporto i punti del modello in cui ci sono riferimenti a tale pagina.

2024-05-31 14:47 UTC, arturu commented
Lunedì mattina apro una issue su https://github.com/italia/designers.italia.it per proporre di allineare/aggiornare l'architettura rispetto a come è qua su pagine statiche

2024-06-02 08:48 UTC, icbrs commented
Anche io sposo la tesi di @arturu. La suddivisione precedente è molto più dettagliata e precisa e fornisce informazioni utili a chi visualizza il sito. 
La nostra pagina si presenta così: https://www.icbrigatasassari.edu.it/scuola/le-persone e dà subito un'idea di come siano distribuite le persone all'interno delle strutture.
Nell'altro modo, forse più aderente all'attuale modello architetturale, c'è solo una suddivisione fra personale docente e non docente che poi richiederebbe ulteriori suddivisioni.

2024-06-11 08:19 UTC, zetareticoli requested changes
Attualmente non prevediamo modifiche al layout della pagina "Le persone" rimanendo fedeli a quello attualmente disponibile. 

@sviluppoRobyone dovresti fare un revert del template HTML modificato.

Tutte le altre modifiche vanno bene invece.

2024-06-11 09:48 UTC, zetareticoli approved these changes

2024-07-16 09:17 UTC, zetareticoli commented
@sviluppoRobyone le altre modifiche proposte restano valide?

2024-07-16 15:05 UTC, danielenole commented
@arturu @sviluppoRobyone vorrei chiarire che l'alberatura indica la posizione delle pagine nella struttura del sito (e questa ricalca la tassonomia dei ruoli presente nel doc di architettura), che influenzerà le url e le breadcrumbs di pagina. Diverso invece è il contenuto e come viene presentato sulla pagina "Le persone". Concordo che la prima versione del template presenta in maniera più chiare le informazioni. Ogni ente può comunque apportare modifiche autonome al template per ricalcare al meglio l'organizzazione interna della scuola.

2024-07-18 08:28 UTC, zetareticoli commented
@sviluppoRobyone attendo di sapere se sul resto dei fix posso procedere

2024-07-22 06:29 UTC, sviluppoRobyone commented
Per noi si può procedere

2024-07-23 13:54 UTC, zetareticoli approved these changes

2024-07-23 13:54 UTC, merged